// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bedservice.proto

package com.smartbed.grpc;

/**
 * Protobuf type {@code grpc.AddPatientRequest}
 */
public  final class AddPatientRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc.AddPatientRequest)
    AddPatientRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddPatientRequest.newBuilder() to construct.
  private AddPatientRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddPatientRequest() {
    first_ = "";
    last_ = "";
    pps_ = "";
    gender_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddPatientRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            first_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            last_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            pps_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            gender_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartbed.grpc.BedServiceImpl.internal_static_grpc_AddPatientRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartbed.grpc.BedServiceImpl.internal_static_grpc_AddPatientRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartbed.grpc.AddPatientRequest.class, com.smartbed.grpc.AddPatientRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code grpc.AddPatientRequest.Gender}
   */
  public enum Gender
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MALE = 0;</code>
     */
    MALE(0),
    /**
     * <code>FEMALE = 1;</code>
     */
    FEMALE(1),
    /**
     * <code>UNSPECIFIED = 2;</code>
     */
    UNSPECIFIED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MALE = 0;</code>
     */
    public static final int MALE_VALUE = 0;
    /**
     * <code>FEMALE = 1;</code>
     */
    public static final int FEMALE_VALUE = 1;
    /**
     * <code>UNSPECIFIED = 2;</code>
     */
    public static final int UNSPECIFIED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gender valueOf(int value) {
      return forNumber(value);
    }

    public static Gender forNumber(int value) {
      switch (value) {
        case 0: return MALE;
        case 1: return FEMALE;
        case 2: return UNSPECIFIED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gender>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gender> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
            public Gender findValueByNumber(int number) {
              return Gender.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.smartbed.grpc.AddPatientRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gender[] VALUES = values();

    public static Gender valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gender(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:grpc.AddPatientRequest.Gender)
  }

  public static final int FIRST_FIELD_NUMBER = 1;
  private volatile java.lang.Object first_;
  /**
   * <code>string first = 1;</code>
   */
  public java.lang.String getFirst() {
    java.lang.Object ref = first_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      first_ = s;
      return s;
    }
  }
  /**
   * <code>string first = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFirstBytes() {
    java.lang.Object ref = first_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      first_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_FIELD_NUMBER = 2;
  private volatile java.lang.Object last_;
  /**
   * <code>string last = 2;</code>
   */
  public java.lang.String getLast() {
    java.lang.Object ref = last_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      last_ = s;
      return s;
    }
  }
  /**
   * <code>string last = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLastBytes() {
    java.lang.Object ref = last_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      last_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PPS_FIELD_NUMBER = 3;
  private volatile java.lang.Object pps_;
  /**
   * <code>string pps = 3;</code>
   */
  public java.lang.String getPps() {
    java.lang.Object ref = pps_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pps_ = s;
      return s;
    }
  }
  /**
   * <code>string pps = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPpsBytes() {
    java.lang.Object ref = pps_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pps_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 4;
  private int gender_;
  /**
   * <code>.grpc.AddPatientRequest.Gender gender = 4;</code>
   */
  public int getGenderValue() {
    return gender_;
  }
  /**
   * <code>.grpc.AddPatientRequest.Gender gender = 4;</code>
   */
  public com.smartbed.grpc.AddPatientRequest.Gender getGender() {
    @SuppressWarnings("deprecation")
    com.smartbed.grpc.AddPatientRequest.Gender result = com.smartbed.grpc.AddPatientRequest.Gender.valueOf(gender_);
    return result == null ? com.smartbed.grpc.AddPatientRequest.Gender.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFirstBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, first_);
    }
    if (!getLastBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, last_);
    }
    if (!getPpsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, pps_);
    }
    if (gender_ != com.smartbed.grpc.AddPatientRequest.Gender.MALE.getNumber()) {
      output.writeEnum(4, gender_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFirstBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, first_);
    }
    if (!getLastBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, last_);
    }
    if (!getPpsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, pps_);
    }
    if (gender_ != com.smartbed.grpc.AddPatientRequest.Gender.MALE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, gender_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartbed.grpc.AddPatientRequest)) {
      return super.equals(obj);
    }
    com.smartbed.grpc.AddPatientRequest other = (com.smartbed.grpc.AddPatientRequest) obj;

    boolean result = true;
    result = result && getFirst()
        .equals(other.getFirst());
    result = result && getLast()
        .equals(other.getLast());
    result = result && getPps()
        .equals(other.getPps());
    result = result && gender_ == other.gender_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FIRST_FIELD_NUMBER;
    hash = (53 * hash) + getFirst().hashCode();
    hash = (37 * hash) + LAST_FIELD_NUMBER;
    hash = (53 * hash) + getLast().hashCode();
    hash = (37 * hash) + PPS_FIELD_NUMBER;
    hash = (53 * hash) + getPps().hashCode();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + gender_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartbed.grpc.AddPatientRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartbed.grpc.AddPatientRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartbed.grpc.AddPatientRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartbed.grpc.AddPatientRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartbed.grpc.AddPatientRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartbed.grpc.AddPatientRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartbed.grpc.AddPatientRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartbed.grpc.AddPatientRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartbed.grpc.AddPatientRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartbed.grpc.AddPatientRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartbed.grpc.AddPatientRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartbed.grpc.AddPatientRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartbed.grpc.AddPatientRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.AddPatientRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.AddPatientRequest)
      com.smartbed.grpc.AddPatientRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartbed.grpc.BedServiceImpl.internal_static_grpc_AddPatientRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartbed.grpc.BedServiceImpl.internal_static_grpc_AddPatientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartbed.grpc.AddPatientRequest.class, com.smartbed.grpc.AddPatientRequest.Builder.class);
    }

    // Construct using com.smartbed.grpc.AddPatientRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      first_ = "";

      last_ = "";

      pps_ = "";

      gender_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartbed.grpc.BedServiceImpl.internal_static_grpc_AddPatientRequest_descriptor;
    }

    @java.lang.Override
    public com.smartbed.grpc.AddPatientRequest getDefaultInstanceForType() {
      return com.smartbed.grpc.AddPatientRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartbed.grpc.AddPatientRequest build() {
      com.smartbed.grpc.AddPatientRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartbed.grpc.AddPatientRequest buildPartial() {
      com.smartbed.grpc.AddPatientRequest result = new com.smartbed.grpc.AddPatientRequest(this);
      result.first_ = first_;
      result.last_ = last_;
      result.pps_ = pps_;
      result.gender_ = gender_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartbed.grpc.AddPatientRequest) {
        return mergeFrom((com.smartbed.grpc.AddPatientRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartbed.grpc.AddPatientRequest other) {
      if (other == com.smartbed.grpc.AddPatientRequest.getDefaultInstance()) return this;
      if (!other.getFirst().isEmpty()) {
        first_ = other.first_;
        onChanged();
      }
      if (!other.getLast().isEmpty()) {
        last_ = other.last_;
        onChanged();
      }
      if (!other.getPps().isEmpty()) {
        pps_ = other.pps_;
        onChanged();
      }
      if (other.gender_ != 0) {
        setGenderValue(other.getGenderValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartbed.grpc.AddPatientRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartbed.grpc.AddPatientRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object first_ = "";
    /**
     * <code>string first = 1;</code>
     */
    public java.lang.String getFirst() {
      java.lang.Object ref = first_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        first_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string first = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstBytes() {
      java.lang.Object ref = first_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        first_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string first = 1;</code>
     */
    public Builder setFirst(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      first_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string first = 1;</code>
     */
    public Builder clearFirst() {
      
      first_ = getDefaultInstance().getFirst();
      onChanged();
      return this;
    }
    /**
     * <code>string first = 1;</code>
     */
    public Builder setFirstBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      first_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object last_ = "";
    /**
     * <code>string last = 2;</code>
     */
    public java.lang.String getLast() {
      java.lang.Object ref = last_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        last_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string last = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastBytes() {
      java.lang.Object ref = last_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        last_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string last = 2;</code>
     */
    public Builder setLast(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      last_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string last = 2;</code>
     */
    public Builder clearLast() {
      
      last_ = getDefaultInstance().getLast();
      onChanged();
      return this;
    }
    /**
     * <code>string last = 2;</code>
     */
    public Builder setLastBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      last_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object pps_ = "";
    /**
     * <code>string pps = 3;</code>
     */
    public java.lang.String getPps() {
      java.lang.Object ref = pps_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pps_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string pps = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPpsBytes() {
      java.lang.Object ref = pps_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pps_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pps = 3;</code>
     */
    public Builder setPps(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      pps_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pps = 3;</code>
     */
    public Builder clearPps() {
      
      pps_ = getDefaultInstance().getPps();
      onChanged();
      return this;
    }
    /**
     * <code>string pps = 3;</code>
     */
    public Builder setPpsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      pps_ = value;
      onChanged();
      return this;
    }

    private int gender_ = 0;
    /**
     * <code>.grpc.AddPatientRequest.Gender gender = 4;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.grpc.AddPatientRequest.Gender gender = 4;</code>
     */
    public Builder setGenderValue(int value) {
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.AddPatientRequest.Gender gender = 4;</code>
     */
    public com.smartbed.grpc.AddPatientRequest.Gender getGender() {
      @SuppressWarnings("deprecation")
      com.smartbed.grpc.AddPatientRequest.Gender result = com.smartbed.grpc.AddPatientRequest.Gender.valueOf(gender_);
      return result == null ? com.smartbed.grpc.AddPatientRequest.Gender.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc.AddPatientRequest.Gender gender = 4;</code>
     */
    public Builder setGender(com.smartbed.grpc.AddPatientRequest.Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      gender_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc.AddPatientRequest.Gender gender = 4;</code>
     */
    public Builder clearGender() {
      
      gender_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc.AddPatientRequest)
  }

  // @@protoc_insertion_point(class_scope:grpc.AddPatientRequest)
  private static final com.smartbed.grpc.AddPatientRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartbed.grpc.AddPatientRequest();
  }

  public static com.smartbed.grpc.AddPatientRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddPatientRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddPatientRequest>() {
    @java.lang.Override
    public AddPatientRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddPatientRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddPatientRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddPatientRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartbed.grpc.AddPatientRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

