// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bedservice.proto

package com.smartbed.grpc;

public interface AddPatientResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.AddPatientResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   */
  int getResult();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
