// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bedservice.proto

package com.smartbed.grpc;

public final class BedServiceImpl {
  private BedServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CurrentBedUsageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CurrentBedUsageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_CurrentBedUsageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_CurrentBedUsageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_UploadPatientImageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_UploadPatientImageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_ImageInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_ImageInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_UploadPatientImageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_UploadPatientImageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_AddPatientRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_AddPatientRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_AddPatientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_AddPatientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020bedservice.proto\022\004grpc\"2\n\026CurrentBedUs" +
      "ageRequest\022\013\n\003min\030\001 \001(\005\022\013\n\003max\030\002 \001(\005\"+\n\027" +
      "CurrentBedUsageResponse\022\020\n\010bedCount\030\001 \001(" +
      "\005\"Y\n\031UploadPatientImageRequest\022\037\n\004info\030\001" +
      " \001(\0132\017.grpc.ImageInfoH\000\022\023\n\tchunkData\030\002 \001" +
      "(\014H\000B\006\n\004data\"+\n\tImageInfo\022\013\n\003pps\030\001 \001(\t\022\021" +
      "\n\timageType\030\002 \001(\t\"7\n\032UploadPatientImageR" +
      "esponse\022\013\n\003pps\030\001 \001(\t\022\014\n\004size\030\002 \001(\005\"\236\001\n\021A" +
      "ddPatientRequest\022\r\n\005first\030\001 \001(\t\022\014\n\004last\030" +
      "\002 \001(\t\022\013\n\003pps\030\003 \001(\t\022.\n\006gender\030\004 \001(\0162\036.grp" +
      "c.AddPatientRequest.Gender\"/\n\006Gender\022\010\n\004" +
      "MALE\020\000\022\n\n\006FEMALE\020\001\022\017\n\013UNSPECIFIED\020\002\"5\n\022A" +
      "ddPatientResponse\022\016\n\006result\030\001 \001(\005\022\017\n\007mes" +
      "sage\030\002 \001(\t2\200\002\n\nBedService\022A\n\nAddPatient\022" +
      "\027.grpc.AddPatientRequest\032\030.grpc.AddPatie" +
      "ntResponse\"\000\022[\n\022UploadPatientImage\022\037.grp" +
      "c.UploadPatientImageRequest\032 .grpc.Uploa" +
      "dPatientImageResponse\"\000(\001\022R\n\017CurrentBedU" +
      "sage\022\034.grpc.CurrentBedUsageRequest\032\035.grp" +
      "c.CurrentBedUsageResponse\"\0000\001B%\n\021com.sma" +
      "rtbed.grpcB\016BedServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_CurrentBedUsageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_CurrentBedUsageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CurrentBedUsageRequest_descriptor,
        new java.lang.String[] { "Min", "Max", });
    internal_static_grpc_CurrentBedUsageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_CurrentBedUsageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_CurrentBedUsageResponse_descriptor,
        new java.lang.String[] { "BedCount", });
    internal_static_grpc_UploadPatientImageRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_UploadPatientImageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_UploadPatientImageRequest_descriptor,
        new java.lang.String[] { "Info", "ChunkData", "Data", });
    internal_static_grpc_ImageInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_ImageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_ImageInfo_descriptor,
        new java.lang.String[] { "Pps", "ImageType", });
    internal_static_grpc_UploadPatientImageResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_grpc_UploadPatientImageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_UploadPatientImageResponse_descriptor,
        new java.lang.String[] { "Pps", "Size", });
    internal_static_grpc_AddPatientRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_grpc_AddPatientRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_AddPatientRequest_descriptor,
        new java.lang.String[] { "First", "Last", "Pps", "Gender", });
    internal_static_grpc_AddPatientResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_grpc_AddPatientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_AddPatientResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
