// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bedservice.proto

package com.smartbed.grpc;

public interface CurrentBedUsageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CurrentBedUsageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 min = 1;</code>
   */
  int getMin();

  /**
   * <code>int32 max = 2;</code>
   */
  int getMax();
}
