// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bedservice.proto

package com.smartbed.grpc;

public interface CurrentBedUsageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.CurrentBedUsageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bedCount = 1;</code>
   */
  int getBedCount();
}
