// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bedservice.proto

package com.smartbed.grpc;

public interface ImageInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.ImageInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pps = 1;</code>
   */
  java.lang.String getPps();
  /**
   * <code>string pps = 1;</code>
   */
  com.google.protobuf.ByteString
      getPpsBytes();

  /**
   * <code>string imageType = 2;</code>
   */
  java.lang.String getImageType();
  /**
   * <code>string imageType = 2;</code>
   */
  com.google.protobuf.ByteString
      getImageTypeBytes();
}
