// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commsservice.proto

package com.smartbed.grpc;

public interface SendMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.SendMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
