// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commsservice.proto

package com.smartbed.grpc;

public interface UpdateChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.UpdateChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
