// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commsservice.proto

package com.smartbed.grpc;

public interface UpdateChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.UpdateChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();
}
