// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bedservice.proto

package com.smartbed.grpc;

public interface UploadPatientImageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.UploadPatientImageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pps = 1;</code>
   */
  java.lang.String getPps();
  /**
   * <code>string pps = 1;</code>
   */
  com.google.protobuf.ByteString
      getPpsBytes();

  /**
   * <code>int32 size = 2;</code>
   */
  int getSize();
}
